databases:
  - name: django_render_db2
    region: singapore
    plan: free
    databaseName: django_render_db2
    user: django_user

services:
  - type: web
    name: quiz_project
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn quiz_project.wsgi:application'
    plan: free
    branch: deploy5
    healthCheckPath: /quiz/expt1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_render_db2
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true